/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin-profile-screen`; params?: Router.UnknownInputParams; } | { pathname: `/ambulance-tracking-screen`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-details-screen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/auth-screen` | `/auth-screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/dashboard-screen` | `/dashboard-screen`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/utils/auth-storage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/admin-profile-screen`; params?: Router.UnknownOutputParams; } | { pathname: `/ambulance-tracking-screen`; params?: Router.UnknownOutputParams; } | { pathname: `/hospital-details-screen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/auth-screen` | `/auth-screen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/dashboard-screen` | `/dashboard-screen`; params?: Router.UnknownOutputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/auth-storage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/admin-profile-screen${`?${string}` | `#${string}` | ''}` | `/ambulance-tracking-screen${`?${string}` | `#${string}` | ''}` | `/hospital-details-screen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/auth-screen${`?${string}` | `#${string}` | ''}` | `/auth-screen${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/dashboard-screen${`?${string}` | `#${string}` | ''}` | `/dashboard-screen${`?${string}` | `#${string}` | ''}` | `/context/AuthContext${`?${string}` | `#${string}` | ''}` | `/utils/auth-storage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin-profile-screen`; params?: Router.UnknownInputParams; } | { pathname: `/ambulance-tracking-screen`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-details-screen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/auth-screen` | `/auth-screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/dashboard-screen` | `/dashboard-screen`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/utils/auth-storage`; params?: Router.UnknownInputParams; };
    }
  }
}
